/**
 * Copyright 2015 Groupon.com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.arpnetworking.remet.gui.expressions;

import java.util.UUID;

/**
 * Interface describing an expression.
 *
 * @author Ville Koskela (vkoskela at groupon dot com)
 */
public interface Expression {

    /**
     * The unique identifier of the expression.
     *
     * @return The unique identifier of the expression.
     */
    UUID getId();

    /**
     * The name of the cluster in the statistic generated by the expression.
     *
     * @return The name of the cluster in the statistic generated by the expression.
     */
    String getCluster();

    /**
     * The name of the service in the statistic generated by the expression.
     *
     * @return The name of the service in the statistic generated by the expression.
     */
    String getService();

    /**
     * The name of the metric in the statistic generated by the expression.
     *
     * @return The name of the metric in the statistic generated by the expression.
     */
    String getMetric();

    /**
     * The script that defines how to determine the expression value.
     *
     * @return The script that defines how to determine the expression value.
     */
    String getScript();
}
