/*
 * Copyright 2014 Groupon.com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* istanbul ignore next */ //ignores inheritance snippet emitted by the TS compiler

///<reference path='defs/metrics.d.ts'/>
import tsdDef = require("tsdDef");
import tsd = require("tsd-metrics-client");
import tsdUtils = require("./utils");
import sample = require("./tsd-metric-sample");
import units = require("./tsd-units");

//aliases
import TsdMetricSample = sample.TsdMetricSample;
import Units = units.Units;

/**
 * Class for timer. Instances are started on creation and record state when
 * stopped or closed.
 *
 * Each timer instance is bound to a [TsdMetrics]{@linkcode module:tsd-metrics-client~TsdMetrics} instance. After the
 * [TsdMetrics]{@linkcode module:tsd-metrics-client~TsdMetrics} instance is closed any timing data generated by
 * <code>Timer</code> instances bound to that [TsdMetrics]{@linkcode module:tsd-metrics-client~TsdMetrics} instance will
 * be discarded.
 *
 * @class
 * @alias Timer
 * @author Mohammed Kamel (mkamel at groupon dot com)
 */
export class TsdTimer extends TsdMetricSample implements tsdDef.Timer {

    private isStoppedFlag:boolean = false;
    private startTime:number = tsdUtils.getNanoTime();

    /**
     * Constructor.
     *
     * @param {string} name Name of the timer
     * @param {MetricsStateObject} metricsStateObject Object holding state of the original metrics object.
     */
    constructor(private name:string, private metricsStateObject:tsd.MetricsStateObject) {
        super(0, Units.NANOSECOND)
    }

    /**
     * Return if the timer was stopped already.
     *
     * @method
     * @return {boolean} Whether the timer was stopped or not.
     */
    public isStopped():boolean {
        return this.isStoppedFlag;
    }

    /**
     * Stop the timer and record timing data in the associated.
     *
     * @method
     * @emits 'error' if the metrics object is closed or if the timer already stopped.
     */
    public stop():void {
        var canStop =
            this.metricsStateObject.assertIsOpen("Cannot stop timer '" + this.name + "'") &&
            this.metricsStateObject.assert(!this.isStopped(), "Timer '" + this.name + "' stopped multiple times")

        if (canStop) {
            this.isStoppedFlag = true;
            (<any>this).value = tsdUtils.getNanoTime() - this.startTime;
        }
    }
}

export class ExplicitTimer extends TsdMetricSample implements tsdDef.Timer {

    /**
     * Constructor.
     *
     * @param name name of the timer
     * @param {MetricsStateObject} metricsStateObject Metrics state object.
     */
    constructor(value:number, unit:tsdDef.Unit, private name:string, private metricsStateObject:tsd.MetricsStateObject) {
        super(value, unit);
    }

    /**
     * Do nothing.
     */
    /* istanbul ignore next */
    public stop():void {
        //Do nothing
        this.metricsStateObject.assert(false, "cannot stop and explicitly set timer");
    }

    /**
     * Always is stopped.
     */
    public isStopped():boolean {
        return true;
    }
}
