{
 "title": "Cluster Aggregator",
 "tags": [ "CAGG" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "service", "query": "cluster_aggregator" },
   { "name": "cluster", "query": "metrics_dev" }
  ]
 },
 "panels": [
  {
   "title": "Metrics Data",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Volume Per Second" }
   ],
   "targets": [
    {
     "alias": "samples",
     "aliasMode": "custom",
     "currentHorizontalAggregatorName": "max",
     "downsampling": "avg",
     "groupBy": { "timeInterval": "1s" },
     "horAggregator": {
      "factor": "1",
      "percentile": "0.75",
      "samplingRate": "1s",
      "target": "0.25",
      "trim": "both",
      "unit": "millisecond"
     },
     "horizontalAggregators": [
      { "name": "max", "sampling_rate": "1m" }
     ],
     "metric": "sinks/periodic_statistics/host_emitter_periodic_statistics_sink/metric_samples",
     "tags": { "cluster": [ "$cluster" ], "service": [ "$service" ] }
    },
    {
     "alias": "metrics",
     "aliasMode": "custom",
     "currentHorizontalAggregatorName": "max",
     "downsampling": "avg",
     "groupBy": { "timeInterval": "1s" },
     "horAggregator": {
      "factor": "1",
      "percentile": "0.75",
      "samplingRate": "1s",
      "target": "0.25",
      "trim": "both",
      "unit": "millisecond"
     },
     "horizontalAggregators": [
      { "name": "max", "sampling_rate": "1m" }
     ],
     "metric": "sinks/periodic_statistics/host_emitter_periodic_statistics_sink/unique_metrics",
     "tags": { "cluster": [ "$cluster" ], "service": [ "$service" ] }
    },
    {
     "alias": "statistics",
     "aliasMode": "custom",
     "currentHorizontalAggregatorName": "max",
     "downsampling": "avg",
     "groupBy": { "timeInterval": "1s" },
     "horAggregator": {
      "factor": "1",
      "percentile": "0.75",
      "samplingRate": "1s",
      "target": "0.25",
      "trim": "both",
      "unit": "millisecond"
     },
     "horizontalAggregators": [
      { "name": "max", "sampling_rate": "1m" }
     ],
     "metric": "sinks/periodic_statistics/host_emitter_periodic_statistics_sink/unique_statistics",
     "tags": { "cluster": [ "$cluster" ], "service": [ "$service" ] }
    },
    {
     "alias": "age",
     "aliasMode": "custom",
     "currentHorizontalAggregatorName": "max",
     "downsampling": "avg",
     "groupBy": { "timeInterval": "1s" },
     "horAggregator": {
      "factor": "1",
      "percentile": "0.75",
      "samplingRate": "1s",
      "target": "0.25",
      "trim": "both",
      "unit": "millisecond"
     },
     "horizontalAggregators": [
      { "name": "max", "sampling_rate": "1m" }
     ],
     "metric": "sinks/periodic_statistics/host_emitter_periodic_statistics_sink/age",
     "tags": { "cluster": [ "$cluster" ], "service": [ "$service" ] }
    }
   ]
  },
  {
   "title": "V1 Post Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s", "label": "Request Latency" }
   ],
   "targets": [
    {
     "alias": "count",
     "aliasMode": "custom",
     "currentGroupByType": "tag",
     "currentHorizontalAggregatorName": "count",
     "downsampling": "avg",
     "groupBy": { "tagKey": "", "timeInterval": "1s" },
     "horAggregator": {
      "factor": "1",
      "percentile": "0.75",
      "samplingRate": "1s",
      "target": "0.25",
      "trim": "both",
      "unit": "millisecond"
     },
     "horizontalAggregators": [
      { "name": "count", "sampling_rate": "1m" }
     ],
     "metric": "rest_service/POST/metrics/v1/data/request",
     "tags": { "cluster": [ "$cluster" ], "service": [ "$service" ] }
    },
    {
     "alias": "p50",
     "aliasMode": "custom",
     "currentHorizontalAggregatorName": "percentile",
     "downsampling": "avg",
     "groupBy": { "timeInterval": "1s" },
     "horAggregator": {
      "factor": "1",
      "percentile": "0.75",
      "samplingRate": "1s",
      "target": "0.25",
      "trim": "both",
      "unit": "millisecond"
     },
     "horizontalAggregators": [
      { "name": "percentile", "percentile": "0.50", "sampling_rate": "1m" }
     ],
     "metric": "rest_service/POST/metrics/v1/data/request",
     "tags": { "cluster": [ "$cluster" ], "service": [ "$service" ] }
    },
    {
     "alias": "p75",
     "aliasMode": "custom",
     "currentHorizontalAggregatorName": "percentile",
     "downsampling": "avg",
     "groupBy": { "timeInterval": "1s" },
     "horAggregator": {
      "factor": "1",
      "percentile": "0.75",
      "samplingRate": "1s",
      "target": "0.25",
      "trim": "both",
      "unit": "millisecond"
     },
     "horizontalAggregators": [
      { "name": "percentile", "percentile": "0.75", "sampling_rate": "1m" }
     ],
     "metric": "rest_service/POST/metrics/v1/data/request",
     "tags": { "cluster": [ "$cluster" ], "service": [ "$service" ] }
    },
    {
     "alias": "p90",
     "aliasMode": "custom",
     "currentHorizontalAggregatorName": "percentile",
     "downsampling": "avg",
     "groupBy": { "timeInterval": "1s" },
     "horAggregator": {
      "factor": "1",
      "percentile": "0.75",
      "samplingRate": "1s",
      "target": "0.25",
      "trim": "both",
      "unit": "millisecond"
     },
     "horizontalAggregators": [
      { "name": "percentile", "percentile": "0.90", "sampling_rate": "1m" }
     ],
     "metric": "rest_service/POST/metrics/v1/data/request",
     "tags": { "cluster": [ "$cluster" ], "service": [ "$service" ] }
    }
   ]
  },
  {
   "title": "V1 Post Request Latency",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "alias": "rest_service/POST/metrics/v1/data/request",
     "aliasMode": "default",
     "currentHorizontalAggregatorName": "merge",
     "downsampling": "avg",
     "groupBy": { "timeInterval": "1s" },
     "horAggregator": {
      "factor": "1",
      "percentile": "0.75",
      "samplingRate": "1s",
      "target": "0.25",
      "trim": "both",
      "unit": "millisecond"
     },
     "horizontalAggregators": [
      { "name": "merge", "sampling_rate": "1m" }
     ],
     "metric": "rest_service/POST/metrics/v1/data/request",
     "tags": { "cluster": [ "$cluster" ], "service": [ "$service" ] }
    }
   ]
  },
  {
   "title": "V1 Post Request Payload Size",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 8 },
   "targets": [
    {
     "alias": "rest_service/POST/metrics/v1/data/body_size",
     "aliasMode": "default",
     "currentHorizontalAggregatorName": "merge",
     "downsampling": "avg",
     "groupBy": { "timeInterval": "1s" },
     "horAggregator": {
      "factor": "1",
      "percentile": "0.75",
      "samplingRate": "1s",
      "target": "0.25",
      "trim": "both",
      "unit": "millisecond"
     },
     "horizontalAggregators": [
      { "name": "merge", "sampling_rate": "1m" }
     ],
     "metric": "rest_service/POST/metrics/v1/data/body_size",
     "tags": { "cluster": [ "$cluster" ], "service": [ "$service" ] }
    }
   ]
  },
  {
   "title": "V1 Post Responses",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "alias": "2xx",
     "aliasMode": "custom",
     "currentHorizontalAggregatorName": "sum",
     "downsampling": "avg",
     "groupBy": { "timeInterval": "1s" },
     "horAggregator": {
      "factor": "1",
      "percentile": "0.75",
      "samplingRate": "1s",
      "target": "0.25",
      "trim": "both",
      "unit": "millisecond"
     },
     "horizontalAggregators": [
      { "name": "sum", "sampling_rate": "1m" }
     ],
     "metric": "rest_service/POST/metrics/v1/data/status/2xx",
     "tags": { "cluster": [ "$cluster" ], "service": [ "$service" ] }
    },
    {
     "alias": "3xx",
     "aliasMode": "custom",
     "currentHorizontalAggregatorName": "sum",
     "downsampling": "avg",
     "groupBy": { "timeInterval": "1s" },
     "horAggregator": {
      "factor": "1",
      "percentile": "0.75",
      "samplingRate": "1s",
      "target": "0.25",
      "trim": "both",
      "unit": "millisecond"
     },
     "horizontalAggregators": [
      { "name": "sum", "sampling_rate": "1m" }
     ],
     "metric": "rest_service/POST/metrics/v1/data/status/3xx",
     "tags": { "cluster": [ "$cluster" ], "service": [ "$service" ] }
    },
    {
     "alias": "4xx",
     "aliasMode": "custom",
     "currentHorizontalAggregatorName": "sum",
     "downsampling": "avg",
     "groupBy": { "timeInterval": "1s" },
     "horAggregator": {
      "factor": "1",
      "percentile": "0.75",
      "samplingRate": "1s",
      "target": "0.25",
      "trim": "both",
      "unit": "millisecond"
     },
     "horizontalAggregators": [
      { "name": "sum", "sampling_rate": "1m" }
     ],
     "metric": "rest_service/POST/metrics/v1/data/status/4xx",
     "tags": { "cluster": [ "$cluster" ], "service": [ "$service" ] }
    },
    {
     "alias": "5xx",
     "aliasMode": "custom",
     "currentHorizontalAggregatorName": "sum",
     "downsampling": "avg",
     "groupBy": { "timeInterval": "1s" },
     "horAggregator": {
      "factor": "1",
      "percentile": "0.75",
      "samplingRate": "1s",
      "target": "0.25",
      "trim": "both",
      "unit": "millisecond"
     },
     "horizontalAggregators": [
      { "name": "sum", "sampling_rate": "1m" }
     ],
     "metric": "rest_service/POST/metrics/v1/data/status/5xx",
     "tags": { "cluster": [ "$cluster" ], "service": [ "$service" ] }
    }
   ]
  },
  {
   "title": "JVM Garbage Collection",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "s", "label": "Collections Per Second" }
   ],
   "targets": [
    {
     "alias": "g1_old_generation_count",
     "aliasMode": "custom",
     "currentHorizontalAggregatorName": "sum",
     "downsampling": "avg",
     "groupBy": { "timeInterval": "1s" },
     "horAggregator": {
      "factor": "1",
      "percentile": "0.75",
      "samplingRate": "1s",
      "target": "0.25",
      "trim": "both",
      "unit": "millisecond"
     },
     "horizontalAggregators": [
      { "name": "sum", "sampling_rate": "1m" }
     ],
     "metric": "jvm/garbage_collector/g1_old_generation/collection_count_delta",
     "tags": { "cluster": [ "$cluster" ], "service": [ "$service" ] }
    },
    {
     "alias": "g1_young_generation_count",
     "aliasMode": "custom",
     "currentHorizontalAggregatorName": "sum",
     "downsampling": "avg",
     "groupBy": { "timeInterval": "1s" },
     "horAggregator": {
      "factor": "1",
      "percentile": "0.75",
      "samplingRate": "1s",
      "target": "0.25",
      "trim": "both",
      "unit": "millisecond"
     },
     "horizontalAggregators": [
      { "name": "sum", "sampling_rate": "1s" }
     ],
     "metric": "jvm/garbage_collector/g1_young_generation/collection_count_delta",
     "tags": { "cluster": [ "$cluster" ], "service": [ "$service" ] }
    },
    {
     "alias": "g1_old_generation_time",
     "aliasMode": "custom",
     "currentHorizontalAggregatorName": "max",
     "downsampling": "avg",
     "groupBy": { "timeInterval": "1s" },
     "horAggregator": {
      "factor": "1",
      "percentile": "0.75",
      "samplingRate": "1s",
      "target": "0.25",
      "trim": "both",
      "unit": "millisecond"
     },
     "horizontalAggregators": [
      { "name": "max", "sampling_rate": "1m" }
     ],
     "metric": "jvm/garbage_collector/g1_old_generation/collection_time",
     "tags": { "cluster": [ "$cluster" ], "service": [ "$service" ] }
    },
    {
     "alias": "g1_young_generation_time",
     "aliasMode": "custom",
     "currentHorizontalAggregatorName": "max",
     "downsampling": "avg",
     "groupBy": { "timeInterval": "1s" },
     "horAggregator": {
      "factor": "1",
      "percentile": "0.75",
      "samplingRate": "1s",
      "target": "0.25",
      "trim": "both",
      "unit": "millisecond"
     },
     "horizontalAggregators": [
      { "name": "max", "sampling_rate": "1m" }
     ],
     "metric": "jvm/garbage_collector/g1_young_generation/collection_time",
     "tags": { "cluster": [ "$cluster" ], "service": [ "$service" ] }
    }
   ]
  },
  {
   "title": "JVM Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "decbytes", "label": "Heap Memory" }
   ],
   "targets": [
    {
     "alias": "heap",
     "aliasMode": "custom",
     "currentHorizontalAggregatorName": "max",
     "downsampling": "avg",
     "groupBy": { "timeInterval": "1s" },
     "horAggregator": {
      "factor": "1",
      "percentile": "0.75",
      "samplingRate": "1s",
      "target": "0.25",
      "trim": "both",
      "unit": "millisecond"
     },
     "horizontalAggregators": [
      { "name": "max", "sampling_rate": "1m" }
     ],
     "metric": "jvm/heap_memory/used",
     "tags": { "cluster": [ "$cluster" ], "service": [ "$service" ] }
    },
    {
     "alias": "code_cache",
     "aliasMode": "custom",
     "currentHorizontalAggregatorName": "max",
     "downsampling": "avg",
     "groupBy": { "timeInterval": "1s" },
     "horAggregator": {
      "factor": "1",
      "percentile": "0.75",
      "samplingRate": "1s",
      "target": "0.25",
      "trim": "both",
      "unit": "millisecond"
     },
     "horizontalAggregators": [
      { "name": "max", "sampling_rate": "1m" }
     ],
     "metric": "jvm/non_heap_memory/code_cache/used",
     "tags": { "cluster": [ "$cluster" ], "service": [ "$service" ] }
    },
    {
     "alias": "compressed_class_space",
     "aliasMode": "custom",
     "currentHorizontalAggregatorName": "max",
     "downsampling": "avg",
     "groupBy": { "timeInterval": "1s" },
     "horAggregator": {
      "factor": "1",
      "percentile": "0.75",
      "samplingRate": "1s",
      "target": "0.25",
      "trim": "both",
      "unit": "millisecond"
     },
     "horizontalAggregators": [
      { "name": "max", "sampling_rate": "1m" }
     ],
     "metric": "jvm/non_heap_memory/compressed_class_space/used",
     "tags": { "cluster": [ "$cluster" ], "service": [ "$service" ] }
    },
    {
     "alias": "g1_eden_space",
     "aliasMode": "custom",
     "currentHorizontalAggregatorName": "max",
     "downsampling": "avg",
     "groupBy": { "timeInterval": "1s" },
     "horAggregator": {
      "factor": "1",
      "percentile": "0.75",
      "samplingRate": "1s",
      "target": "0.25",
      "trim": "both",
      "unit": "millisecond"
     },
     "horizontalAggregators": [
      { "name": "max", "sampling_rate": "1m" }
     ],
     "metric": "jvm/non_heap_memory/g1_eden_space/used",
     "tags": { "cluster": [ "$cluster" ], "service": [ "$service" ] }
    },
    {
     "alias": "g1_old_gen",
     "aliasMode": "custom",
     "currentHorizontalAggregatorName": "max",
     "downsampling": "avg",
     "groupBy": { "timeInterval": "1s" },
     "horAggregator": {
      "factor": "1",
      "percentile": "0.75",
      "samplingRate": "1s",
      "target": "0.25",
      "trim": "both",
      "unit": "millisecond"
     },
     "horizontalAggregators": [
      { "name": "max", "sampling_rate": "1m" }
     ],
     "metric": "jvm/non_heap_memory/g1_old_gen/used",
     "tags": { "cluster": [ "$cluster" ], "service": [ "$service" ] }
    },
    {
     "alias": "g1_survivor_space",
     "aliasMode": "custom",
     "currentHorizontalAggregatorName": "max",
     "downsampling": "avg",
     "groupBy": { "timeInterval": "1s" },
     "horAggregator": {
      "factor": "1",
      "percentile": "0.75",
      "samplingRate": "1s",
      "target": "0.25",
      "trim": "both",
      "unit": "millisecond"
     },
     "horizontalAggregators": [
      { "name": "max", "sampling_rate": "1m" }
     ],
     "metric": "jvm/non_heap_memory/g1_survivor_space/used",
     "tags": { "cluster": [ "$cluster" ], "service": [ "$service" ] }
    },
    {
     "alias": "metaspace",
     "aliasMode": "custom",
     "currentHorizontalAggregatorName": "max",
     "downsampling": "avg",
     "groupBy": { "timeInterval": "1s" },
     "horAggregator": {
      "factor": "1",
      "percentile": "0.75",
      "samplingRate": "1s",
      "target": "0.25",
      "trim": "both",
      "unit": "millisecond"
     },
     "horizontalAggregators": [
      { "name": "max", "sampling_rate": "1m" }
     ],
     "metric": "jvm/non_heap_memory/metaspace/used",
     "tags": { "cluster": [ "$cluster" ], "service": [ "$service" ] }
    }
   ]
  }
 ]
}