{
 "title": "Telegraf",
 "tags": [ "Telegraf" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "description": "Utilization across all cores",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "nice",
     "aliasMode": "custom",
     "currentHorizontalAggregatorName": "max",
     "downsampling": "avg",
     "groupBy": { "timeInterval": "1s" },
     "horAggregator": {
      "factor": "1",
      "percentile": "0.75",
      "samplingRate": "1s",
      "target": "0.25",
      "trim": "both",
      "unit": "millisecond"
     },
     "horizontalAggregators": [
      { "name": "max", "sampling_rate": "1m" }
     ],
     "metric": "cpu/usage_nice",
     "tags": { "cluster": [ "metrics_dev" ] }
    },
    {
     "alias": "guest_nice",
     "aliasMode": "custom",
     "currentHorizontalAggregatorName": "max",
     "downsampling": "avg",
     "groupBy": { "timeInterval": "1s" },
     "horAggregator": {
      "factor": "1",
      "percentile": "0.75",
      "samplingRate": "1s",
      "target": "0.25",
      "trim": "both",
      "unit": "millisecond"
     },
     "horizontalAggregators": [
      { "name": "max", "sampling_rate": "1m" }
     ],
     "metric": "cpu/usage_guest_nice",
     "tags": { "cluster": [ "metrics_dev" ] }
    },
    {
     "alias": "steal",
     "aliasMode": "custom",
     "currentHorizontalAggregatorName": "max",
     "downsampling": "avg",
     "groupBy": { "timeInterval": "1s" },
     "horAggregator": {
      "factor": "1",
      "percentile": "0.75",
      "samplingRate": "1s",
      "target": "0.25",
      "trim": "both",
      "unit": "millisecond"
     },
     "horizontalAggregators": [
      { "name": "max", "sampling_rate": "1m" }
     ],
     "metric": "cpu/usage_steal",
     "tags": { "cluster": [ "metrics_dev" ] }
    },
    {
     "alias": "guest",
     "aliasMode": "custom",
     "currentHorizontalAggregatorName": "min",
     "downsampling": "avg",
     "groupBy": { "timeInterval": "1s" },
     "horAggregator": {
      "factor": "1",
      "percentile": "0.75",
      "samplingRate": "1s",
      "target": "0.25",
      "trim": "both",
      "unit": "millisecond"
     },
     "horizontalAggregators": [
      { "name": "min", "sampling_rate": "1m" }
     ],
     "metric": "cpu/usage_guest",
     "tags": { "cluster": [ "metrics_dev" ] }
    },
    {
     "alias": "iowait",
     "aliasMode": "custom",
     "currentHorizontalAggregatorName": "max",
     "downsampling": "avg",
     "groupBy": { "timeInterval": "1s" },
     "horAggregator": {
      "factor": "1",
      "percentile": "0.75",
      "samplingRate": "1s",
      "target": "0.25",
      "trim": "both",
      "unit": "millisecond"
     },
     "horizontalAggregators": [
      { "name": "max", "sampling_rate": "1m" }
     ],
     "metric": "cpu/usage_iowait",
     "tags": { "cluster": [ "metrics_dev" ] }
    },
    {
     "alias": "irq",
     "aliasMode": "custom",
     "currentHorizontalAggregatorName": "max",
     "downsampling": "avg",
     "groupBy": { "timeInterval": "1s" },
     "horAggregator": {
      "factor": "1",
      "percentile": "0.75",
      "samplingRate": "1s",
      "target": "0.25",
      "trim": "both",
      "unit": "millisecond"
     },
     "horizontalAggregators": [
      { "name": "max", "sampling_rate": "1m" }
     ],
     "metric": "cpu/usage_irq",
     "tags": { "cluster": [ "metrics_dev" ] }
    },
    {
     "alias": "softirq",
     "aliasMode": "custom",
     "currentHorizontalAggregatorName": "max",
     "downsampling": "avg",
     "groupBy": { "timeInterval": "1s" },
     "horAggregator": {
      "factor": "1",
      "percentile": "0.75",
      "samplingRate": "1s",
      "target": "0.25",
      "trim": "both",
      "unit": "millisecond"
     },
     "horizontalAggregators": [
      { "name": "max", "sampling_rate": "1m" }
     ],
     "metric": "cpu/usage_softirq",
     "tags": { "cluster": [ "metrics_dev" ] }
    },
    {
     "alias": "system",
     "aliasMode": "custom",
     "currentHorizontalAggregatorName": "avg",
     "downsampling": "avg",
     "groupBy": { "timeInterval": "1s" },
     "horAggregator": {
      "factor": "1",
      "percentile": "0.75",
      "samplingRate": "1s",
      "target": "0.25",
      "trim": "both",
      "unit": "millisecond"
     },
     "horizontalAggregators": [
      { "name": "avg", "sampling_rate": "1m" }
     ],
     "metric": "cpu/usage_system",
     "tags": { "cluster": [ "metrics_dev" ] }
    },
    {
     "alias": "user",
     "aliasMode": "custom",
     "currentHorizontalAggregatorName": "max",
     "downsampling": "avg",
     "groupBy": { "timeInterval": "1s" },
     "horAggregator": {
      "factor": "1",
      "percentile": "0.75",
      "samplingRate": "1s",
      "target": "0.25",
      "trim": "both",
      "unit": "millisecond"
     },
     "horizontalAggregators": [
      { "name": "max", "sampling_rate": "1m" }
     ],
     "metric": "cpu/usage_user",
     "tags": { "cluster": [ "metrics_dev" ] }
    },
    {
     "alias": "idle",
     "aliasMode": "custom",
     "currentHorizontalAggregatorName": "max",
     "downsampling": "avg",
     "groupBy": { "timeInterval": "1s" },
     "horAggregator": {
      "factor": "1",
      "percentile": "0.75",
      "samplingRate": "1s",
      "target": "0.25",
      "trim": "both",
      "unit": "millisecond"
     },
     "horizontalAggregators": [
      { "name": "max", "sampling_rate": "1m" }
     ],
     "metric": "cpu/usage_idle",
     "tags": { "cluster": [ "metrics_dev" ] }
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "alias": "available_percent_min",
     "aliasMode": "custom",
     "currentHorizontalAggregatorName": "min",
     "downsampling": "avg",
     "groupBy": { "timeInterval": "1s" },
     "horAggregator": {
      "factor": "1",
      "percentile": "0.75",
      "samplingRate": "1s",
      "target": "0.25",
      "trim": "both",
      "unit": "millisecond"
     },
     "horizontalAggregators": [
      { "name": "min", "sampling_rate": "1m" }
     ],
     "metric": "mem/available_percent",
     "tags": { "cluster": [ "metrics_dev" ] }
    },
    {
     "alias": "available_percent_max",
     "aliasMode": "custom",
     "currentHorizontalAggregatorName": "max",
     "downsampling": "avg",
     "groupBy": { "timeInterval": "1s" },
     "horAggregator": {
      "factor": "1",
      "percentile": "0.75",
      "samplingRate": "1s",
      "target": "0.25",
      "trim": "both",
      "unit": "millisecond"
     },
     "horizontalAggregators": [
      { "name": "max", "sampling_rate": "1m" }
     ],
     "metric": "mem/available_percent",
     "tags": { "cluster": [ "metrics_dev" ] }
    },
    {
     "alias": "used",
     "aliasMode": "custom",
     "currentHorizontalAggregatorName": "max",
     "downsampling": "avg",
     "groupBy": { "timeInterval": "1s" },
     "horAggregator": {
      "factor": "1",
      "percentile": "0.75",
      "samplingRate": "1s",
      "target": "0.25",
      "trim": "both",
      "unit": "millisecond"
     },
     "horizontalAggregators": [
      { "name": "max", "sampling_rate": "1m" }
     ],
     "metric": "mem/used",
     "tags": { "cluster": [ "metrics_dev" ] }
    },
    {
     "alias": "wired",
     "aliasMode": "custom",
     "currentHorizontalAggregatorName": "max",
     "downsampling": "avg",
     "groupBy": { "timeInterval": "1s" },
     "horAggregator": {
      "factor": "1",
      "percentile": "0.75",
      "samplingRate": "1s",
      "target": "0.25",
      "trim": "both",
      "unit": "millisecond"
     },
     "horizontalAggregators": [
      { "name": "max", "sampling_rate": "1m" }
     ],
     "metric": "mem/wired",
     "tags": { "cluster": [ "metrics_dev" ] }
    },
    {
     "alias": "slab",
     "aliasMode": "custom",
     "currentHorizontalAggregatorName": "max",
     "downsampling": "avg",
     "groupBy": { "timeInterval": "1s" },
     "horAggregator": {
      "factor": "1",
      "percentile": "0.75",
      "samplingRate": "1s",
      "target": "0.25",
      "trim": "both",
      "unit": "millisecond"
     },
     "horizontalAggregators": [
      { "name": "max", "sampling_rate": "1m" }
     ],
     "metric": "mem/slab",
     "tags": { "cluster": [ "metrics_dev" ] }
    },
    {
     "alias": "cached",
     "aliasMode": "custom",
     "currentHorizontalAggregatorName": "max",
     "downsampling": "avg",
     "groupBy": { "timeInterval": "1s" },
     "horAggregator": {
      "factor": "1",
      "percentile": "0.75",
      "samplingRate": "1s",
      "target": "0.25",
      "trim": "both",
      "unit": "millisecond"
     },
     "horizontalAggregators": [
      { "name": "max", "sampling_rate": "1m" }
     ],
     "metric": "mem/cached",
     "tags": { "cluster": [ "metrics_dev" ] }
    },
    {
     "alias": "buffered",
     "aliasMode": "custom",
     "currentHorizontalAggregatorName": "max",
     "downsampling": "avg",
     "groupBy": { "timeInterval": "1s" },
     "horAggregator": {
      "factor": "1",
      "percentile": "0.75",
      "samplingRate": "1s",
      "target": "0.25",
      "trim": "both",
      "unit": "millisecond"
     },
     "horizontalAggregators": [
      { "name": "max", "sampling_rate": "1m" }
     ],
     "metric": "mem/buffered",
     "tags": { "cluster": [ "metrics_dev" ] }
    },
    {
     "alias": "free",
     "aliasMode": "custom",
     "currentHorizontalAggregatorName": "max",
     "downsampling": "avg",
     "groupBy": { "timeInterval": "1s" },
     "horAggregator": {
      "factor": "1",
      "percentile": "0.75",
      "samplingRate": "1s",
      "target": "0.25",
      "trim": "both",
      "unit": "millisecond"
     },
     "horizontalAggregators": [
      { "name": "max", "sampling_rate": "1m" }
     ],
     "metric": "mem/free",
     "tags": { "cluster": [ "metrics_dev" ] }
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "description": "Across all non-loopback interfaces",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes", "label": "Bytes Per Second" }
   ],
   "targets": [
    {
     "alias": "bytes_sent",
     "aliasMode": "custom",
     "currentGroupByType": "tag",
     "currentHorizontalAggregatorName": "scale",
     "downsampling": "avg",
     "groupBy": { "timeInterval": "1s" },
     "horAggregator": {
      "factor": "1",
      "percentile": "0.75",
      "samplingRate": "1s",
      "target": "0.25",
      "trim": "both",
      "unit": "millisecond"
     },
     "horizontalAggregators": [
      { "name": "max", "sampling_rate": "1m" },
      { "name": "diff" },
      { "factor": "0.016666666666667", "name": "scale" }
     ],
     "metric": "net/bytes_sent",
     "tags": { "cluster": [ "metrics_dev" ] }
    },
    {
     "alias": "bytes_recv",
     "aliasMode": "custom",
     "currentHorizontalAggregatorName": "scale",
     "downsampling": "avg",
     "groupBy": { "timeInterval": "1s" },
     "horAggregator": {
      "factor": "1",
      "percentile": "0.75",
      "samplingRate": "1s",
      "target": "0.25",
      "trim": "both",
      "unit": "millisecond"
     },
     "horizontalAggregators": [
      { "name": "max", "sampling_rate": "1m" },
      { "name": "diff" },
      { "factor": "0.016666666666667", "name": "scale" }
     ],
     "metric": "net/bytes_recv",
     "tags": { "cluster": [ "metrics_dev" ] }
    }
   ]
  },
  {
   "title": "TCP",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Sockets" }
   ],
   "targets": [
    {
     "alias": "closing",
     "aliasMode": "custom",
     "currentHorizontalAggregatorName": "max",
     "downsampling": "avg",
     "groupBy": { "timeInterval": "1s" },
     "horAggregator": {
      "factor": "1",
      "percentile": "0.75",
      "samplingRate": "1s",
      "target": "0.25",
      "trim": "both",
      "unit": "millisecond"
     },
     "horizontalAggregators": [
      { "name": "max", "sampling_rate": "1m" }
     ],
     "metric": "netstat/tcp_closing",
     "tags": { "cluster": [ "metrics_dev" ] }
    },
    {
     "alias": "close",
     "aliasMode": "custom",
     "currentHorizontalAggregatorName": "max",
     "downsampling": "avg",
     "groupBy": { "timeInterval": "1s" },
     "horAggregator": {
      "factor": "1",
      "percentile": "0.75",
      "samplingRate": "1s",
      "target": "0.25",
      "trim": "both",
      "unit": "millisecond"
     },
     "horizontalAggregators": [
      { "name": "max", "sampling_rate": "1m" }
     ],
     "metric": "netstat/tcp_close",
     "tags": { "cluster": [ "metrics_dev" ] }
    },
    {
     "alias": "close_wait",
     "aliasMode": "custom",
     "currentHorizontalAggregatorName": "max",
     "downsampling": "avg",
     "groupBy": { "timeInterval": "1s" },
     "horAggregator": {
      "factor": "1",
      "percentile": "0.75",
      "samplingRate": "1s",
      "target": "0.25",
      "trim": "both",
      "unit": "millisecond"
     },
     "horizontalAggregators": [
      { "name": "max", "sampling_rate": "1m" }
     ],
     "metric": "netstat/tcp_close_wait",
     "tags": { "cluster": [ "metrics_dev" ] }
    },
    {
     "alias": "fin_wait1",
     "aliasMode": "custom",
     "currentHorizontalAggregatorName": "max",
     "downsampling": "avg",
     "groupBy": { "timeInterval": "1s" },
     "horAggregator": {
      "factor": "1",
      "percentile": "0.75",
      "samplingRate": "1s",
      "target": "0.25",
      "trim": "both",
      "unit": "millisecond"
     },
     "horizontalAggregators": [
      { "name": "max", "sampling_rate": "1m" }
     ],
     "metric": "netstat/tcp_fin_wait1",
     "tags": { "cluster": [ "metrics_dev" ] }
    },
    {
     "alias": "fin_wait2",
     "aliasMode": "custom",
     "currentHorizontalAggregatorName": "max",
     "downsampling": "avg",
     "groupBy": { "timeInterval": "1s" },
     "horAggregator": {
      "factor": "1",
      "percentile": "0.75",
      "samplingRate": "1s",
      "target": "0.25",
      "trim": "both",
      "unit": "millisecond"
     },
     "horizontalAggregators": [
      { "name": "max", "sampling_rate": "1m" }
     ],
     "metric": "netstat/tcp_fin_wait2",
     "tags": { "cluster": [ "metrics_dev" ] }
    },
    {
     "alias": "time_wait",
     "aliasMode": "custom",
     "currentHorizontalAggregatorName": "max",
     "downsampling": "avg",
     "groupBy": { "timeInterval": "1s" },
     "horAggregator": {
      "factor": "1",
      "percentile": "0.75",
      "samplingRate": "1s",
      "target": "0.25",
      "trim": "both",
      "unit": "millisecond"
     },
     "horizontalAggregators": [
      { "name": "max", "sampling_rate": "1m" }
     ],
     "metric": "netstat/tcp_time_wait",
     "tags": { "cluster": [ "metrics_dev" ] }
    },
    {
     "alias": "listen",
     "aliasMode": "custom",
     "currentHorizontalAggregatorName": "max",
     "downsampling": "avg",
     "groupBy": { "timeInterval": "1s" },
     "horAggregator": {
      "factor": "1",
      "percentile": "0.75",
      "samplingRate": "1s",
      "target": "0.25",
      "trim": "both",
      "unit": "millisecond"
     },
     "horizontalAggregators": [
      { "name": "max", "sampling_rate": "1m" }
     ],
     "metric": "netstat/tcp_listen",
     "tags": { "cluster": [ "metrics_dev" ] }
    },
    {
     "alias": "established",
     "aliasMode": "custom",
     "currentHorizontalAggregatorName": "max",
     "downsampling": "avg",
     "groupBy": { "timeInterval": "1s" },
     "horAggregator": {
      "factor": "1",
      "percentile": "0.75",
      "samplingRate": "1s",
      "target": "0.25",
      "trim": "both",
      "unit": "millisecond"
     },
     "horizontalAggregators": [
      { "name": "max", "sampling_rate": "1m" }
     ],
     "metric": "netstat/tcp_established",
     "tags": { "cluster": [ "metrics_dev" ] }
    }
   ]
  },
  {
   "title": "Disk Space",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "decbytes", "label": "Utilization" }
   ],
   "targets": [
    {
     "alias": "used",
     "aliasMode": "custom",
     "currentHorizontalAggregatorName": "max",
     "downsampling": "avg",
     "groupBy": { "timeInterval": "1s" },
     "horAggregator": {
      "factor": "1",
      "percentile": "0.75",
      "samplingRate": "1s",
      "target": "0.25",
      "trim": "both",
      "unit": "millisecond"
     },
     "horizontalAggregators": [
      { "name": "max", "sampling_rate": "1m" }
     ],
     "metric": "disk/used",
     "tags": { "cluster": [ "metrics_dev" ] }
    },
    {
     "alias": "free",
     "aliasMode": "custom",
     "currentHorizontalAggregatorName": "max",
     "downsampling": "avg",
     "groupBy": { "timeInterval": "1s" },
     "horAggregator": {
      "factor": "1",
      "percentile": "0.75",
      "samplingRate": "1s",
      "target": "0.25",
      "trim": "both",
      "unit": "millisecond"
     },
     "horizontalAggregators": [
      { "name": "max", "sampling_rate": "1m" }
     ],
     "metric": "disk/free",
     "tags": { "cluster": [ "metrics_dev" ] }
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "graph",
   "description": "Across all disks",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "decbytes", "label": "Bytes Per Second" }
   ],
   "targets": [
    {
     "alias": "read_bytes",
     "aliasMode": "custom",
     "currentHorizontalAggregatorName": "scale",
     "downsampling": "avg",
     "groupBy": { "timeInterval": "1s" },
     "horAggregator": {
      "factor": "1",
      "percentile": "0.75",
      "samplingRate": "1s",
      "target": "0.25",
      "trim": "both",
      "unit": "millisecond"
     },
     "horizontalAggregators": [
      { "name": "max", "sampling_rate": "1m" },
      { "name": "diff" },
      { "factor": "0.016666666666667", "name": "scale" }
     ],
     "metric": "diskio/read_bytes",
     "tags": { "cluster": [ "metrics_dev" ] }
    },
    {
     "alias": "write_bytes",
     "aliasMode": "custom",
     "currentHorizontalAggregatorName": "scale",
     "downsampling": "avg",
     "groupBy": { "timeInterval": "1s" },
     "horAggregator": {
      "factor": "1",
      "percentile": "0.75",
      "samplingRate": "1s",
      "target": "0.25",
      "trim": "both",
      "unit": "millisecond"
     },
     "horizontalAggregators": [
      { "name": "max", "sampling_rate": "1m" },
      { "name": "diff" },
      { "factor": "0.016666666666667", "name": "scale" }
     ],
     "metric": "diskio/write_bytes",
     "tags": { "cluster": [ "metrics_dev" ] }
    },
    {
     "alias": "read_time",
     "aliasMode": "custom",
     "currentHorizontalAggregatorName": "scale",
     "downsampling": "avg",
     "groupBy": { "timeInterval": "1s" },
     "horAggregator": {
      "factor": "1",
      "percentile": "0.75",
      "samplingRate": "1s",
      "target": "0.25",
      "trim": "both",
      "unit": "millisecond"
     },
     "horizontalAggregators": [
      { "name": "max", "sampling_rate": "1m" },
      { "name": "diff" },
      { "factor": "0.016666666666667", "name": "scale" }
     ],
     "metric": "diskio/read_time",
     "tags": { "cluster": [ "metrics_dev" ] }
    },
    {
     "alias": "write_time",
     "aliasMode": "custom",
     "currentHorizontalAggregatorName": "scale",
     "downsampling": "avg",
     "groupBy": { "timeInterval": "1s" },
     "horAggregator": {
      "factor": "1",
      "percentile": "0.75",
      "samplingRate": "1s",
      "target": "0.25",
      "trim": "both",
      "unit": "millisecond"
     },
     "horizontalAggregators": [
      { "name": "max", "sampling_rate": "1m" },
      { "name": "diff" },
      { "factor": "0.016666666666667", "name": "scale" }
     ],
     "metric": "diskio/write_time",
     "tags": { "cluster": [ "metrics_dev" ] }
    }
   ]
  }
 ]
}